from logging import getLogger

from midi_sampling.export.abstractions import (
    InstrumentModel,
    InstrumentPatchWriter,
    InstrumentRegion,
    PatchWriteContext,
    PatchWriteOutcome,
)
from midi_sampling.export.exceptions import ExportWriteError

logger = getLogger(__name__)

FORMAT_ID = "sfz"
PATCH_SUFFIX = ".sfz"


class SfzPatchWriter(InstrumentPatchWriter):
    """
    Emit one SFZ file for Sforzando / ARIA.

    Loop points are written as `loop_start` / `loop_end` opcodes (both
    frame indices with an inclusive end, the `smpl` chunk convention),
    so they stay valid for FLAC samples that carry no `smpl` chunk.
    """

    @property
    def format_id(self) -> str:
        return FORMAT_ID

    def write(self, context: PatchWriteContext) -> PatchWriteOutcome:
        instrument = context.instrument
        patch_path = context.output_directory / f"{instrument.name}{PATCH_SUFFIX}"

        content = self._render(instrument)
        try:
            with open(patch_path, "w", encoding="utf-8", newline="\n") as f:
                f.write(content)
        except OSError as e:
            raise ExportWriteError(
                f"{patch_path}: cannot write patch file: {e}"
            ) from e

        logger.debug(
            f"Wrote {patch_path}: {len(instrument.regions)} region(s)"
        )
        return PatchWriteOutcome(patch_path=patch_path)

    def _render(self, instrument: InstrumentModel) -> str:
        lines = [
            f"// {instrument.name}",
            "// Generated by midi-sampling export. Do not edit by hand.",
        ]
        for group in instrument.exclusive_groups:
            lines.append(f"// exclusive group {group.number}: {group.name}")

        lines += [
            "",
            "<global>",
            f"ampeg_attack={instrument.envelope.attack:g}",
            f"ampeg_release={instrument.envelope.release:g}",
        ]

        current_tone: str | None = None
        for region in instrument.regions:
            if region.tone_id != current_tone:
                current_tone = region.tone_id
                lines.append("")
                lines.append(f"// tone: {region.tone_id}")
            lines.append(self._region_line(region))

        return "\n".join(lines) + "\n"

    def _region_line(self, region: InstrumentRegion) -> str:
        opcodes = [f"sample={region.sample_path}"]

        if region.trigger == "release":
            opcodes.append("trigger=release")
            if region.rt_decay is not None:
                opcodes.append(f"rt_decay={region.rt_decay:g}")

        opcodes += [
            f"lokey={region.key_low}",
            f"hikey={region.key_high}",
            f"pitch_keycenter={region.root_note}",
            f"lovel={region.velocity_low}",
            f"hivel={region.velocity_high}",
        ]

        if region.loop is not None:
            opcodes += [
                "loop_mode=loop_continuous",
                f"loop_start={region.loop.start_frame}",
                f"loop_end={region.loop.end_frame}",
            ]
        else:
            opcodes.append("loop_mode=no_loop")

        if region.exclusive_group is not None:
            opcodes += [
                f"group={region.exclusive_group}",
                f"off_by={region.exclusive_group}",
                "off_mode=fast",
            ]

        return "<region> " + " ".join(opcodes)
