from pathlib import Path

from midi_sampling.export.abstractions import (
    InstrumentEnvelope,
    InstrumentExclusiveGroup,
    InstrumentModel,
    InstrumentPatchWriter,
    InstrumentRegion,
    PatchWriteContext,
    RegionLoop,
)
from midi_sampling.export.sfz_impl import SfzPatchWriter

DEFAULT_ENVELOPE = InstrumentEnvelope(attack=0.0, release=0.3)


def make_region(**overrides) -> InstrumentRegion:
    values = dict(
        tone_id="tone-1",
        source_path=Path("processed/tone-1/a.wav"),
        sample_path="Samples/tone-1/a.wav",
        root_note=38,
        key_low=36,
        key_high=40,
        velocity_low=1,
        velocity_high=63,
        loop=None,
        exclusive_group=None,
        trigger="attack",
        rt_decay=None,
    )
    values.update(overrides)
    return InstrumentRegion(**values)


class TestSfzPatchWriter:
    def test_implements_the_patch_writer_base_class(self):
        writer = SfzPatchWriter()
        assert isinstance(writer, InstrumentPatchWriter)
        assert writer.format_id == "sfz"
        assert writer.directory_name == "sfz"
        assert writer.supported_audio_formats is None

    def test_renders_all_opcodes(self, tmp_path: Path):
        instrument = InstrumentModel(
            name="test-instrument",
            envelope=DEFAULT_ENVELOPE,
            regions=(
                make_region(
                    loop=RegionLoop(start_frame=1000, end_frame=2000),
                    exclusive_group=1,
                ),
                make_region(
                    tone_id="tone-2",
                    sample_path="Samples/tone-2/b.flac",
                    root_note=43,
                    key_low=41,
                    key_high=45,
                    velocity_low=64,
                    velocity_high=127,
                    trigger="release",
                    rt_decay=6.0,
                ),
            ),
            exclusive_groups=(InstrumentExclusiveGroup(number=1, name="pair"),),
        )

        outcome = SfzPatchWriter().write(
            PatchWriteContext(instrument=instrument, output_directory=tmp_path)
        )

        assert outcome.patch_path == tmp_path / "test-instrument.sfz"
        content = outcome.patch_path.read_text(encoding="utf-8")
        assert content.splitlines() == [
            "// test-instrument",
            "// Generated by midi-sampling export. Do not edit by hand.",
            "// exclusive group 1: pair",
            "",
            "<global>",
            "ampeg_attack=0",
            "ampeg_release=0.3",
            "",
            "// tone: tone-1",
            "<region> sample=Samples/tone-1/a.wav"
            " lokey=36 hikey=40 pitch_keycenter=38 lovel=1 hivel=63"
            " loop_mode=loop_continuous loop_start=1000 loop_end=2000"
            " group=1 off_by=1 off_mode=fast",
            "",
            "// tone: tone-2",
            "<region> sample=Samples/tone-2/b.flac trigger=release rt_decay=6"
            " lokey=41 hikey=45 pitch_keycenter=43 lovel=64 hivel=127"
            " loop_mode=no_loop",
        ]

    def test_renders_custom_envelope(self, tmp_path: Path):
        instrument = InstrumentModel(
            name="env",
            envelope=InstrumentEnvelope(attack=0.005, release=1.2),
            regions=(make_region(),),
            exclusive_groups=(),
        )

        outcome = SfzPatchWriter().write(
            PatchWriteContext(instrument=instrument, output_directory=tmp_path)
        )

        content = outcome.patch_path.read_text(encoding="utf-8")
        assert "ampeg_attack=0.005" in content
        assert "ampeg_release=1.2" in content

    def test_uses_lf_line_endings(self, tmp_path: Path):
        instrument = InstrumentModel(
            name="lf",
            envelope=DEFAULT_ENVELOPE,
            regions=(make_region(),),
            exclusive_groups=(),
        )

        outcome = SfzPatchWriter().write(
            PatchWriteContext(instrument=instrument, output_directory=tmp_path)
        )

        raw = outcome.patch_path.read_bytes()
        assert b"\r\n" not in raw
        assert raw.endswith(b"\n")
