import os
import sys
import json

import jsonschema2md
import pyperclip

THIS_FILENAME = os.path.basename(__file__)

def json_schema_to_markdown(schema_file_path: str, add_paragraph_count: int = 0) -> str:
    parser = jsonschema2md.Parser(
        examples_as_yaml=False,
        show_examples="all"
    )

    with open(schema_file_path, "r") as f:
        markdown_lines = parser.parse_schema(json.load(f))
        if add_paragraph_count > 0:
            markdown_lines = [("#" * add_paragraph_count) + line if line.startswith('#') else line for line in markdown_lines]

    return ''.join(markdown_lines)

if __name__ == "__main__":

    if len(sys.argv) < 2:
        print("Copy a converted markdown to clipboard.")
        print(f"Usage: python {THIS_FILENAME} <schema_file_path> ...")
        sys.exit(1)

    args = sys.argv[1:]
    HEADER_COMMENT = f"<!-- [END] Generated by documenttool/{THIS_FILENAME} -->\n"
    FOOTER_COMMENT = f"<!-- [END] Generated by documenttool/{THIS_FILENAME} -->\n"

    result = []

    result.append(HEADER_COMMENT)

    for file in args:
        md_txt = json_schema_to_markdown(file, 2)
        result.append(md_txt)

    result.append(HEADER_COMMENT)

    pyperclip.copy(''.join(result))
    print("Copied to clipboard.")
