name: config-validation
on:
  push:
    paths:
      - 'midisampling/appconfig/sampling-config.schema.json'
      - 'midisampling/appconfig/midi-config.schema.json'
      - 'sampling-config.json'
      - 'examples/midi-config.example.json'
jobs:
  config-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv lock

      - name: validate sampling config
        run: |
          pipenv run python -m midisampling.appconfig validate-sampling sampling-config.json

      - name: validate midi config
        run: |
          pipenv run python -m midisampling.appconfig validate-midi examples/midi-config.example.json
